### ISSUE TITLE
Exception has occurred: ValueError

### ISSUE THREAD

**Issue by yorkshire-tea** [michaelshumshum/kahoot-annoyer#1]
hey i got this error most likely my end but i thought i would say if eney one has a solution it would make me most happy  
![image](https://user-images.githubusercontent.com/77109991/103900863-3ebed900-50f0-11eb-8508-15d795af03b9.png)

**Comment by michaelshumshum** [comment]
hmm. in your terminal, can you run the command `stty size`? the only thing this line of code does is get the size of your terminal window. I'm guessing this isn't working for you because you are in Visual Studio Code, which is an IDE. try running the script in another terminal.

**Comment by michaelshumshum** [comment]
never mind. i realized that the command i used is incompatible with windows. i didn't notice this initially since i am on mac.i switched the command for a universal command that will work for all operating systems. download the new file and it should work now.
