### ISSUE TITLE
can you make a vid on how to do this to make it easier add the vid in readme

### ISSUE THREAD

**Issue by justnothi** [michaelshumshum/kahoot-annoyer#4]
please it would be ez

**Comment by justnothi** [comment]
`
![image](https://user-images.githubusercontent.com/80005071/110379259-9ad8a780-8024-11eb-9406-4778a6485791.png)
`

**Comment by justnothi** [comment]
![image](https://user-images.githubusercontent.com/80005071/110379264-9d3b0180-8024-11eb-8419-3567a14f24de.png)

**Comment by michaelshumshum** [comment]
use the other one that is a template. it is more up to date and easier to modify. please dont spam all my repositories or i wont help you.

**Comment by michaelshumshum** [comment]
please stop spamming. i wont help you. figure this out yourself. literally all you need to do is download the code, get all the requirements, and run it.

**Comment by justnothi** [comment]
?

**Comment by justnothi** [comment]
ok
